### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by bagindokemas** [wencolani/IterE#1]
Hi the authors of IterE,

I found an error when I run IterE in my machine. This is the error message:

File "/nobackup/users/r01krw16/IterE/data.py", line 125, in _read_id ent2id_f = open(ent2id_file, 'r') 
FileNotFoundError: [Errno 2] No such file or directory: './datasets/FB15k-237-sparse/entity2id.txt' 

When I check data.py, I also found out that beside entity2id.txt, you should also provide relation2id.txt in this github.

Best Regards.

**Comment by wencolani** [comment]
Hi, 

Thanks for pointing it out. 
We have added the entity2id.txt and relation2id.txt to each dataset. 
Please have a look ;-)

Best,
Wen
