### ISSUE TITLE
problem with tensorflow?

### ISSUE THREAD

**Issue by bagindokemas** [wencolani/IterE#5]
Dear Authors,

I found these error when executing IterE in my gpu machine:
self.pos_triples = tf.placeholder(tf.int32, [None, 3])
AttributeError: module 'tensorflow' has no attribute 'placeholder'

Can you advise me how to solve this error? was it because the version of tensorflow that IterE used different with the version of tensorflow in my gpu machine? If it was the case, I would like to ask about what version of tensorflow that IterE used. 

Thank you

**Comment by SRL94** [comment]
Downgrade your tensorflow to 1.5
